-- AlterTable
ALTER TABLE `delivery` MODIFY `status` ENUM('PENDING', 'CONFIRMED', 'PACKING', 'SHIPPED', 'DELIVERED', 'CANCELLED', 'READY', 'READY_FOR_PICKUP') NOT NULL;

-- AlterTable
ALTER TABLE `order` MODIFY `status` ENUM('PENDING', 'CONFIRMED', 'PACKING', 'SHIPPED', 'DELIVERED', 'CANCELLED', 'READY', 'READY_FOR_PICKUP') NOT NULL DEFAULT 'PENDING';
